[package]
name = "fractal_renderer_shader_vertex64"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
spirv-std.workspace = true
fractal_renderer_shared.workspace = true
